events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  map $http_upgrade $connection_upgrade {
    default upgrade;
    "" close;
  }

  upstream frontend_upstream {
    server frontend:80;
  }

  upstream backend_upstream {
    server backend:3000;
  }

  server {
    listen 80;
    server_name explosive-race.dam.inspedralbes.cat;

    # Redirecció permanent a HTTPS
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    http2 on;
    server_name explosive-race.dam.inspedralbes.cat;

    # Certificats (Mapejats des del host)
    ssl_certificate /etc/letsencrypt/live/explosive-race.dam.inspedralbes.cat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/explosive-race.dam.inspedralbes.cat/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # API i WebSockets
    location /api {
      proxy_pass http://backend_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      
      # Suport per WebSockets (essencial per al joc)
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      
      # Timeouts per mantenir la connexió viva
      proxy_read_timeout 86400s;
      proxy_send_timeout 86400s;
    }

    # Frontend (Landing Page)
    location / {
      proxy_pass http://frontend_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
